In [ ]:
import numpy as np
#Ejercicio 7
#A)
p= 1e34
q = 1
#resultado esperado = 1 ya que tendriamos solo Q 
res = p + q - p
print(res)

#Analisis sin utilizar epsilon
#A que se debe este resultado? Python utiliza 16 cajitas t para expresar los numeros pero como p tiene 35 cajitas nuestro numero 1 muerio absorbido por el numero 
#grande
#si p estaria elevado a la 15 sobreviviria nuestro 1
p = 1e15 # 1000000000000000, = 0,1 x 10^16
res = p + q - p
print(res)

p= 1e34
#Analisis utilizando epsilon
print(np.finfo(float).eps)
#Este seria la distancia entre numeros con python , con lo cual si yo quiero saber el numero el cual cumpla que tenga esta distancia
#deberia hacer Num donde esto parado -> p * Epsilon
print(p*np.finfo(float).eps)

#Si elijo un z que cumple esto no me va a devolver 0
z = (p*np.finfo(float).eps)
print(p + z - p)
#Si elijo un z mas chico que esto me va a devolver 0
z = z* 0.1
print(p + z - p)




0.0
1.0
2.220446049250313e-16
2.220446049250313e+18
2.305843009213694e+18
0.0


In [ ]:
import numpy as np
#Ejercicio 7b
p = 100
q = 1e-15 
print((p + q)+q)
print(((p+q) +q) + q)

z = p * np.finfo(float).eps
print(z)

#Si yo sumo a Q la mitad del umbral para arriba va a pasar al siguiente numero porque paso la mitad de paso y la absorbcion no afecta

print(z/2)

q = q + z/2

print((p + q)+q)
print("--------")
print (p + (2*q))
print (p + (3*q))

100.0
100.0
2.220446049250313e-14
1.1102230246251565e-14
100.00000000000003
--------
100.00000000000003
100.00000000000004


In [ ]:
#C Y  D

# Como el float trabaja con base binaria lo que ocurre es que seguardan 0 y 1 hasta llenar todas las "cajitas" binarias (53) y queda algo de la pinta
# 0.100000000055 con lo cual el redondeo lo va a hacer para arriba
print (0.1+0.2)
#Mientras que este el redondeo da para abajo pero podria no funcionar   
print (0.1+0.3)


print(0.1+0.2 == 0.3)
print(0.1+0.3 == 0.4)



0.30000000000000004
0.4
False
True


In [ ]:
#E Y F
#El ultimo exponente antes de entrar al overflow(agregar 0 en las cajas) es el -308 , como aca ya estamos superando agregamos 0 pero como python tiene 16 cajitas
#nada mas el 323-16 = 307 pero 324 -16 = 308 con lo cual por eso uno nos da 0 y el otro no

print(1e-323)
print(1e-324)


1e-323
0.0


In [ ]:
#g
#epsilon/2 la idea es que si nosotros nos encontramos en el 1 y le sumamos epsilon/2 + un cahcito vamos a estar mas cerca del siguiente numero
# si nos encontramos en el 1 le sumamos epsilon/2 - un cachito vamos a estar mas cerca del uno . Recien la computadora elige del lado de quien esta mas cerca
# cuando esta en una mitad o en otra
# si estamos en el medio la maquina se fija si el ultimo de la cifra es par tirar para bajo si es impar tira para arriba


In [ ]:
#H I J K
# el h) (1 +epsilon/2) + epsilon/2 cae en el caso del redondeo al par mas cercano
#i) 1 +(epsilon/2 + epsilon/2) cae en el siguiente numero
#j) ((1+epsilon/2) +epsilon/2) -1 cae en 0
#k) (1 +(epsilon/2 + epsilon/2)) - 1 cae en 1

In [ ]:
#L Y M 
#Como pi no esta representado con sus infinitos decimales lo que ocurre es que la funcion sen devuelve residuo cuando deberia ser 0

Ejercicio 8
Debido a la idea de que para pasar al siguiente numero debo estar de la mitad del paso para adelante , cuando la seria esta muy avanzada la sumatoria S va a aumentar haciendo mas grande los saltos y como los numeros que vamos a sumar se van haciendo mas chicos va a llegar un momento que la absorbcion haga que la serie no diverga.
Si queremos que la serie sea infinita debemos lograr que la suma de terminos sea mas grande que la mitad de la distancia ya recorrida para que la aritmetica del punto flotante no absorba los numeros.



In [57]:
print(2.00*1/2)
print(3.00*1/2)


1.0
1.5


In [62]:
#Ejercicio 20 a)
import numpy as np

A = np.array([[3,0,0],[0,5/4,3/4],[0,3/4,5/4]])
k = np.linalg.norm(A,np.inf) * np.linalg.norm(np.linalg.inv(A),np.inf)

print(k)

#c)
B = np.array([3,2,2])
x = np.linalg.solve(A,B)

"""
Creo una lista de vectores genericos , de longitud arbitraria (en este caso de -1 a 10) , y procuro que tenga la dim de las col de A -> 3 y en este caso testeo
con 3 vectores
"""
vectores_generados = np.random.uniform(-1,10,size=(100,3))
print(vectores_generados)

"""
Voy a normalizar los vectores para que estos tengan la norma del error de b la cual sale del inciso b

|| b - b*|| / || b || <= 10^4/6  con ||b|| = 3
|| b - b*|| / 3 <= 10^-4/6 -> ||b - b*|| <= 1/2 x 10^-4

"""
cota_b = 1/2 * 10**-4
vectores_normalizados = []

for vector in vectores_generados:
    norma_cruda = np.linalg.norm(vector,np.inf)
    if(norma_cruda != 0): #evito dividir por 0
        vector_normalizado = (vector / norma_cruda) * cota_b #Con la primera division me queda el unitario y luego la mult me da la longitud del error max
        vectores_normalizados.append(vector_normalizado)


res_erroneos = []
for vector in vectores_normalizados:
    res_con_error=np.linalg.solve(A, B + vector)
    res_erroneos.append(res_con_error)

#Ahora resta chequear que se cumpla lo teorico , es decir que la longitud del X erroneo sea la propuesta por el inciso b

chequeo_longitud : list[bool] = []
for x_erroneo in res_erroneos:
    distancia = np.linalg.norm(x-x_erroneo,np.inf)
    if(distancia < 10**-4):
        chequeo_longitud.append(True)
    else:
        chequeo_longitud.append(False)

if (all(chequeo_longitud)):
    print("El teorema se cumplio y nuestra cota vale")
else: 
    print("Algo exploto")


6.0
[[ 2.44174142 -0.6187321   2.66954644]
 [ 6.20901322 -0.73683392  1.82193221]
 [ 3.52702711  6.68830903  5.36970594]
 [-0.21870954  1.05763211  0.68181894]
 [ 6.12846875  3.2935593   9.03939729]
 [-0.66637312  2.48062327  3.76750615]
 [ 1.92922556 -0.37997851  6.80167671]
 [ 5.00145049  6.82390768  0.52744344]
 [ 5.17611274  9.5357725   5.06911798]
 [ 8.85739504  5.93538381  2.55534524]
 [-0.262964    2.95204231  6.53651185]
 [ 1.79340188  7.71996014  8.00059023]
 [ 5.17321635  9.28806015  6.32565553]
 [ 2.04126209  5.93931728  3.70539299]
 [ 0.85452713  4.33250517  1.10478684]
 [ 6.03817504  7.30494724  2.24315786]
 [ 0.01663001  4.4556409  -0.97233837]
 [ 8.30079684  7.38956115  1.22691441]
 [ 4.43169592  0.04294266  5.38949133]
 [ 6.45619329  4.2211221   8.90960133]
 [ 2.0761308   7.33612419  9.75992072]
 [ 8.09175044  3.44156296  4.48434894]
 [ 3.07618286  3.39491706  7.0595448 ]
 [-0.69301193  4.34959842  0.44348566]
 [-0.79012982  6.78538773  8.39587857]
 [ 6.09070285  8.8562